// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UidGenerateClient is the client API for UidGenerate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UidGenerateClient interface {
	UidGenerate(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*UidResponse, error)
}

type uidGenerateClient struct {
	cc grpc.ClientConnInterface
}

func NewUidGenerateClient(cc grpc.ClientConnInterface) UidGenerateClient {
	return &uidGenerateClient{cc}
}

func (c *uidGenerateClient) UidGenerate(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*UidResponse, error) {
	out := new(UidResponse)
	err := c.cc.Invoke(ctx, "/service.UidGenerate/UidGenerate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UidGenerateServer is the server API for UidGenerate service.
// All implementations must embed UnimplementedUidGenerateServer
// for forward compatibility
type UidGenerateServer interface {
	UidGenerate(context.Context, *UidRequest) (*UidResponse, error)
	mustEmbedUnimplementedUidGenerateServer()
}

// UnimplementedUidGenerateServer must be embedded to have forward compatible implementations.
type UnimplementedUidGenerateServer struct {
}

func (UnimplementedUidGenerateServer) UidGenerate(context.Context, *UidRequest) (*UidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UidGenerate not implemented")
}
func (UnimplementedUidGenerateServer) mustEmbedUnimplementedUidGenerateServer() {}

// UnsafeUidGenerateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UidGenerateServer will
// result in compilation errors.
type UnsafeUidGenerateServer interface {
	mustEmbedUnimplementedUidGenerateServer()
}

func RegisterUidGenerateServer(s grpc.ServiceRegistrar, srv UidGenerateServer) {
	s.RegisterService(&UidGenerate_ServiceDesc, srv)
}

func _UidGenerate_UidGenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UidGenerateServer).UidGenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UidGenerate/UidGenerate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UidGenerateServer).UidGenerate(ctx, req.(*UidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UidGenerate_ServiceDesc is the grpc.ServiceDesc for UidGenerate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UidGenerate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.UidGenerate",
	HandlerType: (*UidGenerateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UidGenerate",
			Handler:    _UidGenerate_UidGenerate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service/service.proto",
}
